#17: Create buckets
exasol/bucketfs-java pull request #36
Opened 2021-09-06 15:44 UTC by kaklakariada

Closes #17

2021-09-17 10:38 UTC, redcatbear requested changes

2021-09-17 10:38 UTC, redcatbear commented on src/main/java/com/exasol/bucketfs/jsonrpc/JsonRpcCommandExecutor.java
> +        this.client = client;
You used `Objects.requireNotNull()` in one place, but not here. Why?

2021-09-17 10:38 UTC, redcatbear commented on src/main/java/com/exasol/bucketfs/jsonrpc/JsonRpcCommandExecutor.java
> +    // Must be public for json mapping
```suggestion
    // Must be public for JSON mapping
```

2021-09-17 10:38 UTC, redcatbear commented on src/main/java/com/exasol/bucketfs/jsonrpc/JsonRpcCommandExecutor.java
> +    // Must be public for json mapping
```suggestion
    // Must be public for JSON mapping
```

2021-09-17 10:38 UTC, redcatbear commented on src/main/java/com/exasol/bucketfs/jsonrpc/RpcCommand.java
> + * response payload and return a custom model by implementing {@link #processResult(String)}.
Explain "custom model" in this context, please.

2021-09-17 10:38 UTC, redcatbear commented on src/main/java/com/exasol/bucketfs/jsonrpc/RpcCommand.java
> + * response payload and return a custom model by implementing {@link #processResult(String)}.
Explain "job".

2021-09-17 10:38 UTC, redcatbear commented on src/main/java/com/exasol/bucketfs/jsonrpc/RpcCommand.java
> +     * Parameters for the RPC request. The returned object must be serializable to Json.
```suggestion
     * Parameters for the RPC request.
     * <p>
     * The returned object must be serializable to JSON.
     * </p>
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/BasicAuthAuthenticatorTest.java
> +        assertAuthHeader(requestBuilder, "Basic dXNlcjpwYXNzd29yZA==");
```suggestion
        final var requestBuilder = HttpRequest.newBuilder(new URI("http://localhost"));
        new BasicAuthAuthenticator("user", "password").authenticate(requestBuilder);
        assertAuthHeader(requestBuilder, "Basic dXNlcjpwYXNzd29yZA==");
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/BearerTokenAuthenticatorTest.java
> +    }
```suggestion
    void testAuthenticate() throws URISyntaxException {
        final var requestBuilder = HttpRequest.newBuilder(new URI("http://localhost"));
        new BearerTokenAuthenticator("token").authenticate(requestBuilder);
        assertAuthHeader(requestBuilder, "Bearer token");
    }
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/BearerTokenAuthenticatorTest.java
> +    }
Code duplication. I suggest a static-only assertion class.

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +
```suggestion
class CreateBucketCommandIT extends AbstractBucketIT {
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +                .writePassword(WRITE_PASSWORD);
One line per chain link please.

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +                "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"));
Please wrap in `assertAll`.

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +    void creatingBucketWithCheckingCertificateFails() throws BucketAccessException, TimeoutException {
```suggestion
    void testCreatingBucketWithCheckingCertificateThrowsException() throws BucketAccessException, TimeoutException {
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +    void creatingBucketWithExistingNameFails() throws BucketAccessException, TimeoutException {
```suggestion
    void testCreatingBucketWithExistingNameThrowsException() throws BucketAccessException, TimeoutException {
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +    void createdBucketIsWriteable() throws BucketAccessException, TimeoutException, InterruptedException {
```suggestion
    void testCreatedBucketIsWriteable() throws BucketAccessException, TimeoutException, InterruptedException {
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +    void createdBucketWithDefaultValuesSucceeds() throws BucketAccessException, TimeoutException, InterruptedException {
```suggestion
    void testCreateBucketWithDefaultValues() throws BucketAccessException, TimeoutException, InterruptedException {
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +                "JSON RPC only available with version >= 7, " + version + " is not supported.");
```suggestion
                "JSON RPC only available with Exasol version 7 or later, " + version + " is not supported.");
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +    private String getRandomBucketName() {
```suggestion
    private String getUniqueBucketName() {
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +class CreateBucketCommandIT extends AbstractBucketIT {
Please reorder methods in order of first reference.

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +        assertThat(bucket.listContents(), hasItem(fileName));
Nice. :+1:

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +                fail("Bucket " + bucket.getBucketName() + " not available after " + waitingTime);
```suggestion
                fail("Time out trying to verify that Bucket " + bucket.getBucketName() + " exists after waiting " + waitingTime);
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandIT.java
> +        } catch (final BucketAccessException e) {
```suggestion
        } catch (final BucketAccessException exception) {
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandTest.java
> +
```suggestion
class CreateBucketCommandTest {
```

2021-09-17 10:38 UTC, redcatbear commented on src/test/java/com/exasol/bucketfs/jsonrpc/CreateBucketCommandTest.java
> +    private void asserExecutionFails(final CreateBucketCommandBuilder builder,
```suggestion
    private void assertCreateBucketCommandThrowsExceptionWithMessage(final CreateBucketCommandBuilder builder,
```

2021-09-17 11:12 UTC, kaklakariada commented on .github/workflows/ci-build.yml
> +      - name: Cache SonarQube packages
Already enabled a few lines before

2021-09-17 11:13 UTC, kaklakariada commented on .github/workflows/ci-build.yml
> +        if: ${{ always() }}
No. When there are build errors (e.g. failed tests), the following steps won't be executed.

2021-09-20 06:02 UTC, redcatbear submitted a review, later dismissed

2021-09-20 07:27 UTC, redcatbear approved these changes

2021-09-20 07:29 UTC, merged