dependency updates
exasol/bucketfs-java pull request #43
Opened 2022-05-04 07:02 UTC by jakobbraun

2022-05-04 08:07 UTC, redcatbear submitted a review, later dismissed

2022-05-04 08:07 UTC, redcatbear commented on doc/changes/changes_2.4.0.md
> +* ISSUE_NUMBER: description
issue number missing for update

2022-05-05 07:01 UTC, kaklakariada requested changes

2022-05-05 07:01 UTC, kaklakariada commented on .github/workflows/ci-build.yml
> +        uses: actions/setup-java@v2
```suggestion
        uses: actions/setup-java@v3
```

2022-05-05 07:01 UTC, kaklakariada commented on .github/workflows/ci-build.yml
> +        uses: actions/cache@v2
```suggestion
        uses: actions/cache@v3
```

2022-05-05 07:01 UTC, kaklakariada commented on .github/workflows/ci-build.yml
> +        uses: actions/cache@v2
```suggestion
        uses: actions/cache@v3
```

2022-05-05 07:01 UTC, kaklakariada commented on .github/workflows/ci-build.yml
> +        if: ${{ env.DEFAULT_DB_VERSION == matrix.docker_db_version }}
```suggestion
        if: ${{ env.SONAR_TOKEN != null && env.DEFAULT_DB_VERSION == matrix.docker_db_version }}
```

2022-05-09 11:12 UTC, kaklakariada approved these changes

2022-05-09 11:13 UTC, merged